version: '7cf8205c9f71f9a953de2d586ca7f28cf3383fc2'
services:
    saltbot:
        build:
            dockerfile: Dockerfile
        depends_on:
            - saltdb
    saltdb:
        build:
            context: ./.docker/db
            dockerfile: Dockerfile
        volumes:
            - ./data/postgres:/var/lib/postgres/data
        expose:
            - "5432"
        secrets:
            - ./.docker/secrets.yml
#    TODO: implement as a broad caching layer
#    redis:
#        image: redis
#        volumes:
#            - ./data/redis:/var/lib/redis/data
#        expose:
#            - "6379"

