# Base postgres alpine image
FROM postgres:12-alpine

# The base image runs a lot of shit that is incredibly useful
# Just need single setup afterwards

# USER postgres

# COPY .pgpass /docker-entrypoint-initdb.d/
# RUN ls
# RUN ln -s /docker-entrypoint-initdb.d/.pgpass $HOME/.pgpass && \
#    createuser "$POSTGRES_USER" -d -R -S -p 5432 -w 

